version: '3'
services:
  redis:
    image: eqalpha/keydb:latest
    restart: always
    container_name: kairos-redis
    ports:
      - '6379:6379'
    volumes:
       - redis-data:/data
    
  eventstore:
    image: 'eventstore/eventstore'
    restart: always
    container_name: kairos-eventstore
    ports:
      - '2113:2113'
      - '1113:1113'
    volumes:
       - eventstore-data:/var/lib/eventstore
       - eventstore-data:/var/log/eventstore
volumes:
  eventstore-data:
  eventstore-log:
  redis-data: