version: 2
jobs:
  backend:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
      - image: redislabs/rejson
      - image: eventstore/eventstore

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - root-node_modules-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - root-node_modules-

      - run: yarn

      - save_cache:
          paths:
            - node_modules
          key: root-node_modules-{{ checksum "package.json" }}

      - run: yarn backend:test

  frontend:
    docker:
      - image: circleci/node:10.15

    steps:
      - checkout

      - restore_cache:
          keys:
            - root-node_modules-{{ checksum "package.json" }}
            - root-node_modules-

      - run: cd src/kairos.app
      - run: yarn

      - save_cache:
          paths:
            - src/kairos.app/node_modules
          key: root-node_modules-{{ checksum "package.json" }}

      - run: yarn frontend:lint
      - run: yarn frontend:prettier
      - run: yarn frontend:test
workflows:
  version: 2
  test:
    jobs:
      - backend
      - frontend