version: 2
jobs:
  build:
    docker:
      - image: zeekozhu/aspnetcore-build-yarn:2.2-alpine

    steps:
      - checkout

      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - setup_remote_docker            

      # Download and cache dependencies
      - restore_cache:
          keys:
            - root-node_modules-{{ checksum "package.json" }}
            - root-node_modules-

      - run: yarn

      - save_cache:
          paths:
            - node_modules
            - src/kairos.app/node_modules
          key: root-node_modules-{{ checksum "package.json" }}

      - run: yarn docker:start
      - run: yarn backend:test
      - run: yarn frontend:lint
      - run: yarn frontend:prettier
      - run: yarn frontend:test