apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secrets-patcher
  namespace: kairos
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["get", "list", "patch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-secret-patcher
  namespace: kairos
subjects:
- kind: ServiceAccount
  name: default
  namespace: kairos
roleRef:
  kind: ClusterRole
  name: secrets-patcher
  apiGroup: rbac.authorization.k8s.io