apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api
  namespace: kairos
spec:
  replicas: 1
  selector:
    matchLabels:
      run: web-api    
  template:
    metadata:
      labels:
        run: web-api
    spec:
      volumes:
        - name: web-api-logs-pv
          persistentVolumeClaim:
            claimName: web-api-logs-pv-claim  
      containers:
        - name: web-api
          image: %REGISTRY/kairos/web.api:%VERSION
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: web-api-logs-pv
              mountPath: /Kairos.Web.Api/logs
              subPath: webapilogs
          env:
            - name: Kairos_WriteRepository__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: web-api-secret
                  key: write-db-connectionstring
          envFrom:
            - configMapRef:
                name: web-api-config

      imagePullSecrets:
        - name: regcred
