apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-api-logs-pv-claim
  namespace: kairos
  labels:
    app: web-api
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi