apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: kairos
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
        namespace: kairos
    spec:
      volumes:
        - name: redis-pv
          persistentVolumeClaim:
            claimName: redis-pv-claim
            
      containers:
        - name: redis
          image: redislabs/rejson:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /data
              name: redis-pv
              subPath: data