apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: letsencrypt-job
  namespace: kairos
  labels:
    app: letsencrypt
spec:
  schedule: '0 0 1 * *'
  jobTemplate:
    spec:
      template:
        metadata:
          name: letsencrypt
          labels:
            app: letsencrypt
        spec:
          containers:
          - image: lucax88x/kube-nginx-letsencrypt:latest
            name: letsencrypt
            imagePullPolicy: Always
            ports:
            - name: letsencrypt
              containerPort: 80
            env:
            - name: DOMAINS
              value: kairos.rocks
            - name: EMAIL
              value: luca.trazzi@garaio.com
            - name: SECRET
              value: kairos-tls
            - name: STAGING
              value: 'true'
          restartPolicy: Never